Makefile.am: suppress error for -Wvla-parameter
GCC 11 produces a bogus warning (which is promoted to an error) in common.c:

input/common.c:21:57: error: argument 2 of type ‘int16_t[(int)frames * 2]’ {aka ‘short int[(int)frames * 2]’} declared with mismatched bound ‘(int) frames * 2’ [-Werror=vla-parameter]
   21 | int write_to_fftw_input_buffers(int16_t frames, int16_t buf[frames * 2], void *data) {
      |                                                 ~~~~~~~~^~~~~~~~~~~~~~~
In file included from input/common.c:1:
./input/common.h:42:57: note: previously declared as ‘int16_t[(int)frames * 2]’ {aka ‘short int[(int)frames * 2]’} with bound ‘(int) frames * 2’
   42 | int write_to_fftw_input_buffers(int16_t frames, int16_t buf[frames * 2], void *data);
      |                                                 ~~~~~~~~^~~~~~~~~~~~~~~

Upstream issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97548